#!/usr/bin/env bash
#
# roster.sh — the authoritative list of generated teammate agent NAMES, and the lookup for
# each one's manifest attributes (area, tier, model, color).
#
# Why this exists: the roster used to be discoverable by globbing templates/agents/*.md.tmpl
# (one file per agent). The tiered dev set (be-/fe- x junior/medior/senior) is generated from
# ONE template + templates/agents-manifest.json, so that glob no longer yields the real names
# — it would yield "dev". Every consumer that needs the name list (install.sh, agent-tools.sh,
# agent-block.sh, add-agent.sh) goes through roster_agent_names() instead, so the roster can
# never drift between the generator and the tools that inspect what it generated.
#
# The roster is the UNION of two sources:
#   1. templates/agents-manifest.json  -> .agents[].name   (the tiered dev set)
#   2. templates/agents/*.md.tmpl      -> basename         (standalone agents: ctm-investigator,
#      EXCEPT dev.md.tmpl                                    ctm-playwright-tester)
#
# Custom "tm-*" agents are NOT part of the roster: they are created per project by
# `ctm agent add`, not generated by `ctm init`.

_RO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_MANIFEST="${AGENTS_MANIFEST:-$_RO_ROOT/templates/agents-manifest.json}"
AGENT_TMPL_DIR="${AGENT_TMPL_DIR:-$_RO_ROOT/templates/agents}"

# The template rendered once per manifest entry. Excluded from the standalone glob so it is
# never mistaken for an agent named "dev".
ROSTER_DEV_TMPL_BASENAME="dev"

# roster_manifest_names — names of the generated tier agents, in manifest order.
roster_manifest_names() {
  jq -r '.agents[]?.name // empty' "$AGENTS_MANIFEST" 2>/dev/null || true
}

# roster_standalone_names — names of the agents that still have their own one-off template.
roster_standalone_names() {
  local tmpl name
  for tmpl in "$AGENT_TMPL_DIR"/*.md.tmpl; do
    [[ -e "$tmpl" ]] || continue
    name="$(basename "$tmpl" .md.tmpl)"
    [[ "$name" == "$ROSTER_DEV_TMPL_BASENAME" ]] && continue
    printf '%s\n' "$name"
  done
}

# roster_agent_names — every name `ctm init` installs (tier agents first, then standalone).
roster_agent_names() {
  roster_manifest_names
  roster_standalone_names
}

# roster_is_agent <name> — true if <name> is part of the generated roster.
roster_is_agent() {
  local needle="$1" n
  while IFS= read -r n; do
    [[ "$n" == "$needle" ]] && return 0
  done < <(roster_agent_names)
  return 1
}

# roster_agent_field <name> <field> — a manifest agent's attribute (area|tier|model|color).
# Prints nothing for a standalone agent (they carry their own frontmatter).
roster_agent_field() {
  local name="$1" field="$2"
  jq -r --arg n "$name" --arg f "$field" '
    (.agents[]? | select(.name == $n) | .[$f]) // empty
  ' "$AGENTS_MANIFEST" 2>/dev/null || true
}

# roster_area_field <area> <field> — an area's shared text fragment from the manifest.
roster_area_field() {
  local area="$1" field="$2"
  jq -r --arg a "$area" --arg f "$field" '
    (.areas[$a][$f]) // empty
  ' "$AGENTS_MANIFEST" 2>/dev/null || true
}

# Standalone use: roster.sh names | roster.sh field <name> <field>
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-names}" in
    names) roster_agent_names ;;
    field) shift; roster_agent_field "$@" ;;
    area)  shift; roster_area_field "$@" ;;
    *) echo "usage: roster.sh {names | field <name> <field> | area <area> <field>}" >&2; exit 1 ;;
  esac
fi
