#!/usr/bin/env bash
#
# task.sh — token-efficient CLI for managing the task-manager tasks.json (and context.json).
#
# Goal: Claude Code should NOT re-read/re-write the whole JSON for every operation (expensive
# in tokens); instead it should use terse commands. Every mutation is atomic (temp file + mv),
# and timestamps + history/notes entries are maintained automatically.
#
# Usage:   ./task.sh <command> [arguments]
# Help:    ./task.sh help
#
# The store defaults to the project's .claude/task-manager/ directory; overridable via the
# TM_DIR environment variable (this is how the claude-task-manager wrapper scripts point each
# project at its own data directory).

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration / paths
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=engine/feedback.sh
source "$SCRIPT_DIR/feedback.sh"

# Project root: two levels up from the skill directory (.claude/skills/task-manager -> project).
# Uses git if available, otherwise falls back to the relative path.
default_dir() {
  local root
  if root="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
    echo "$root/.claude/task-manager"
  else
    echo "$SCRIPT_DIR/../../task-manager"
  fi
}

TM_DIR="${TM_DIR:-$(default_dir)}"
TASKS_FILE="$TM_DIR/tasks.json"
CONTEXT_FILE="$TM_DIR/context.json"
BACKUP_FILE="$TM_DIR/tasks.json.bak"
CTX_BACKUP_FILE="$TM_DIR/context.json.bak"
LOCK_DIR="$TM_DIR/.tm.lock"

# --- Agent-notification (inbox) storage ----------------------------------------
# events.jsonl: an append-only event feed (ALONGSIDE the per-task history, not replacing it),
# from which the `inbox <agent>` command returns only NEW events generated by OTHER agents,
# using a per-agent cursor. The PostToolUse hook injects this for the caller automatically.
# This is ADDITIVE: it does not change the existing tasks.json/history logic.
EVENTS_FILE="$TM_DIR/events.jsonl"
CURSORS_DIR="$TM_DIR/.cursors"

VALID_STATUSES="todo in_progress blocked review done"
VALID_PRIORITIES="low normal high urgent"

# The calling agent's name (--as <name>); main() fills this in from the command arguments.
# emit_event writes this as `by`; inbox uses it to filter out the caller's own echo.
ACTOR=""

# --- Shared jq fragments: by / files, used by every note- and status-transition writer ------
# Centralized here so the rule lives in ONE place instead of being copy-pasted into every call
# site that needs it (cmd_add's initial history entry, cmd_status, _try_claim, cmd_review,
# cmd_reopen, cmd_status_many, cmd_note, cmd_handoff).
#
# JQ_BY: null-safe 'by' value. Every caller MUST also pass --arg actor "$ACTOR".
JQ_BY='(if $actor=="" then null else $actor end)'
#
# JQ_NOTE_FILES: a note's own 'files' — the task's CURRENT files minus every file already
# "claimed" by an earlier note (each file is assigned to AT MOST ONE note — claim-once). Assumes
# '.' is the task object, evaluated BEFORE the new note is appended (so .files/.notes still
# reflect the pre-append state).
# LIMITATION (accepted, not a bug — see the by/files task discussion): `files rm <path>`
# followed by `files add <path>` does NOT reopen <path> for claiming — it stays "claimed" by
# whichever earlier note claimed it before the removal, so a later note's delta will not include
# it again. A per-file add-timestamp would fix this, but would turn `files` from a plain string
# array into an object array — a bigger backward-compatibility break than this rare corrective
# case (files rm) warrants.
JQ_NOTE_FILES='((.files // []) - ((.notes // []) | map(.files // []) | add // []))'
#
# JQ_TRANSITION_FILES: the files "claimed" by note(s) since the LAST real status transition —
# deliberately TIMESTAMP-FREE. now_iso() only has second resolution, so comparing timestamps
# could silently drop a note written in the same wall-clock second as the previous transition —
# a common case, since an agent's files-add -> note -> status sequence often completes within a
# single second. Formula: unique( union(ALL note.files) - union(ALL PREVIOUS history entries'
# .files) ). This works BECAUSE note.files is claim-once (see JQ_NOTE_FILES above): every file
# belongs to at most one note, so subtracting everything already attributed to a past transition
# leaves exactly the notes' files written since that transition — no clock involved. Assumes '.'
# is the task object, evaluated BEFORE the new history entry is appended.
JQ_TRANSITION_FILES='((((.notes // []) | map(.files // []) | add // []) - (((.history // []) | map(.files // []) | add) // [])) | unique)'

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

die() { echo "error: $*" >&2; exit 1; }

command -v jq >/dev/null 2>&1 || die "jq is not installed (required for this script)."

now_iso() { date -u +%Y-%m-%dT%H:%M:%S.000Z; }

# --- Concurrency lock (mkdir-based, portable) --------------------------------
# macOS has no built-in flock(1), so we use an atomic mkdir-lock (same pattern as the
# agent-message-bus skill). This means two concurrently-writing agents don't clobber each
# other (last-write-wins is eliminated). The lock is cleaned up by a trap if the process
# exits early.
LOCK_HELD=0

# Determine the lock's age in seconds (based on dir mtime), portably (BSD/macOS
# `stat -f %m`, GNU/Linux `stat -c %Y`). Empty if there's no lock.
lock_age() {
  local m now
  m="$(stat -f %m "$LOCK_DIR" 2>/dev/null || stat -c %Y "$LOCK_DIR" 2>/dev/null || echo "")"
  [[ -z "$m" ]] && { echo ""; return; }
  now="$(date +%s)"
  echo $(( now - m ))
}

acquire_lock() {
  local waited=0 timeout="${TM_LOCK_TIMEOUT:-15}" stale="${TM_LOCK_STALE:-60}"
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    # Remove an orphaned lock ONLY based on age (after a real crash). On the hot path
    # (fast, healthy writers) this never runs, so an active lock is never removed, and two
    # writers can never be in the critical section at once.
    local age; age="$(lock_age)"
    if [[ -n "$age" && "$age" -ge "$stale" ]]; then
      rm -rf "$LOCK_DIR" 2>/dev/null || true
      continue
    fi
    waited=$((waited + 1))
    [[ $waited -ge $((timeout * 20)) ]] && die "could not acquire lock within ${timeout}s: $LOCK_DIR"
    sleep 0.05
  done
  LOCK_HELD=1
  trap release_lock EXIT INT TERM
}
release_lock() {
  [[ "$LOCK_HELD" == "1" ]] && rm -rf "$LOCK_DIR" 2>/dev/null || true
  LOCK_HELD=0
}

# --- Pre-write backup --------------------------------------------------------
# Before every mutation we save the previous state (one generation), so that `restore`
# can undo a broken write.
backup_tasks()   { [[ -f "$TASKS_FILE"   ]] && cp "$TASKS_FILE"   "$BACKUP_FILE"     2>/dev/null || true; }
backup_context() { [[ -f "$CONTEXT_FILE" ]] && cp "$CONTEXT_FILE" "$CTX_BACKUP_FILE" 2>/dev/null || true; }

ensure_tasks_file() {
  if [[ ! -f "$TASKS_FILE" ]]; then
    mkdir -p "$TM_DIR"
    jq -n --arg now "$(now_iso)" \
      '{schemaVersion:1, updatedAt:$now, tasks:[]}' > "$TASKS_FILE"
  fi
}

require_tasks_file() {
  [[ -f "$TASKS_FILE" ]] || die "no tasks.json: $TASKS_FILE (run: task.sh init)"
}

is_valid_status() {
  local s="$1"
  for v in $VALID_STATUSES; do [[ "$s" == "$v" ]] && return 0; done
  return 1
}

# Atomic write: applies a jq filter to TASKS_FILE via a temp file. The filter also updates
# the root updatedAt field.
apply_jq() {
  acquire_lock
  backup_tasks
  local tmp
  tmp="$(mktemp "${TASKS_FILE}.XXXXXX")"
  if jq "$@" "$TASKS_FILE" > "$tmp"; then
    mv "$tmp" "$TASKS_FILE"
  else
    rm -f "$tmp"
    release_lock
    die "jq operation failed."
  fi
  release_lock
}

task_exists() {
  local id="$1"
  [[ "$(jq --arg id "$id" '[.tasks[]|select(.id==$id)]|length' "$TASKS_FILE")" != "0" ]]
}

# --- Event feed (inbox) ----------------------------------------------------
# One line in events.jsonl: {seq, at, by, task, kind, text} (+ optional `to` for a directed
# message). `seq` monotonically increases (the file's line count + 1, consistent under the
# lock). `by` is the calling agent (ACTOR). The optional 4th argument addresses the event to a
# specific agent (handoff / review-request): inbox highlights events whose `to` is the reader.
# Only mutations call this; queries do not generate events. Swallows errors: notification is
# best-effort and should never fail a task operation.
emit_event() {
  local task="$1" kind="$2" text="${3:-}" to="${4:-}"
  [[ -n "$ACTOR" ]] || return 0
  local now; now="$(now_iso)"
  acquire_lock
  mkdir -p "$TM_DIR" 2>/dev/null || true
  touch "$EVENTS_FILE" 2>/dev/null || true
  local seq; seq=$(( $(wc -l < "$EVENTS_FILE" 2>/dev/null || echo 0) + 1 ))
  jq -cn --argjson seq "$seq" --arg at "$now" --arg by "$ACTOR" \
     --arg task "$task" --arg kind "$kind" --arg text "$text" --arg to "$to" \
     '{seq:$seq, at:$at, by:$by, task:$task, kind:$kind, text:$text}
      + (if $to=="" then {} else {to:$to} end)' \
     >> "$EVENTS_FILE" 2>/dev/null || true
  release_lock
}

# --- context.json helpers (same atomic pattern, separate file) ---------

ensure_context_file() {
  if [[ ! -f "$CONTEXT_FILE" ]]; then
    mkdir -p "$TM_DIR"
    jq -n --arg now "$(now_iso)" '{
      schemaVersion:1, updatedAt:$now, initPrompt:"", goal:"",
      currentFocus:"", constraints:[], decisions:[], openQuestions:[], notes:""
    }' > "$CONTEXT_FILE"
  fi
}

require_context_file() {
  [[ -f "$CONTEXT_FILE" ]] || die "no context.json: $CONTEXT_FILE (run: task.sh ctx-init)"
}

# Atomic write to CONTEXT_FILE (like apply_jq, just for the other file).
apply_ctx() {
  acquire_lock
  backup_context
  local tmp
  tmp="$(mktemp "${CONTEXT_FILE}.XXXXXX")"
  if jq "$@" "$CONTEXT_FILE" > "$tmp"; then
    mv "$tmp" "$CONTEXT_FILE"
  else
    rm -f "$tmp"
    release_lock
    die "jq operation failed (context)."
  fi
  release_lock
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_help() {
  cat <<'EOF'
task.sh — token-efficient tasks.json manager

New here? `task.sh guide` walks through end-to-end scenarios ("when X happens, run Y") —
read that first. This is the dry flag-by-flag reference.

STORAGE
  Default: <project>/.claude/task-manager/tasks.json  (override: TM_DIR env)

CALLER IDENTITY (--as) — REQUIRED for every non-meta command
  Add to every call: --as <agent-name>   (your name; the main agent: main).
  This is how the PostToolUse hook knows who to inject fresh events (inbox) for, and it's
  written as every event's `by`. Meta commands are exempt (no --as needed):
  help, inbox, init, validate, restore, raw, lang.
  Example:  task.sh status fix-login done --as backend-auth

NOTIFICATION (inbox — the hook calls this automatically, but you can too)
  inbox <agent>            Events generated by OTHER agents since <agent>'s cursor
                           (not its own), then advances the cursor.
                           SILENT if there's nothing new. The hook appends this as
                           additionalContext.
  lang                     The project's preferred language (set from the board's UI
                           language). REQUIRED once per session — agent templates instruct
                           every agent to call this at session start, if not already done.

QUERIES (non-mutating, terse output)
  list [status] [filters]  Terse list: "<id> [status] (prio) @module title #tag".
                           Filters: --tag <t> --agent <a> --priority <p> --module <m>
                                    --all (include archived)  --json (machine output)
  ids [status] [--all]     Just the ids, one per line (archived excluded unless --all)
  get <id>                 ONE task's full JSON (not the whole file)
  field <id> <field>       The raw value of one field of one task
  summary [--all]          Count by status + total (archived excluded unless --all)
  find <text> [--all]      Title/description search, case-insensitive, terse list
                           (archived excluded unless --all)
  next [--claim]           Your next recommended todo (no open dependency), by priority.
                           Always scoped to the --as caller: only tasks assigned to YOU.
                           For an unscoped overview use `list todo` instead.
                           --claim atomically takes your top ready todo (-> in_progress)
  review-queue [reviewer]  Tasks in review (oldest first) with age; optionally one reviewer's
  stale [--older-than 24h] [status...]
                           Held-but-idle tasks (default in_progress+review) past the threshold
  deps <id>                What this task waits on and what it blocks (dependency view)
  history <id>             One task's history entries, terse
  validate                 Schema check (required fields, status, priority, broken
                           dependency, duplicate id)
  raw                      The whole file (rarely needed — token-expensive)

MUTATIONS (atomic write under mkdir-lock; timestamp + history auto-maintained; pre-write backup)
  init                     Create an empty tasks.json if missing
  add <id> <title> [desc]  New task (todo, priority=normal, tags=[], dependsOn=[])
  status <id> <status> [note]
                           Status change + history entry (todo|in_progress|blocked|review|done)
  status-many <status> <id...>
                           Set multiple tasks to one status, in ONE atomic write
  reopen <id> [status]     Reopen a closed/archived task (default: todo) with history
  note <id> <text>         Append a note ({at,text,by,files}). ALL-CAPS prefix + ':' gets a
                           colored kind-badge on the board: KUTATÁS/RESEARCH, TERV/PLAN,
                           DÖNTÉS/DECISION, IMPL/JAVÍTÁS/FIX/REFAKTOR/REFACTOR, KÉSZ/DONE,
                           BLOKK/BLOCK, FIGYELEM/WARNING, VERIFIKÁLVA/VERIFIED/TESZT/TEST, USER,
                           ÁTADÁS/HANDOFF (keep this list in sync with js/Utils.js's
                           NOTE_KIND_STEMS). Plain text works too.
                           e.g. task.sh note fix-login "KÉSZ: export route javítva" --as backend
  priority <id> <low|normal|high|urgent>
                           Set priority
  tag <id> <add|rm> <tag>
                           Add/remove a label (tags array, unique)
  checklist <id> [add <text>... | done|undo|rm <item-id>...]
                           Checklist/todo items under a task — small steps that don't deserve
                           their own task (no owner, status, or board card). For a real,
                           independent unit of work, use `add`+`dep`/`handoff` instead. No
                           sub-op: list them. Stable ids (c1, c2, ...), never reused.
                           Phrase each item as a short SENTENCE, not a one/two-word label:
                           "patch the null check in Login.php", not "patch" — a bare label
                           tells the next reader nothing they can act on.
  files <id> [add|rm <abs-path>...]
                           Record the source files a task touches (absolute paths, unique).
                           No sub-op: list them. This is a standard duty when working a task.
  module <id> <module>     Set the module/area label (assignedModule) — free text,
                           empty string clears it. Use `list --module <m>` to filter.
  assign <id> <agent>      Set assignedAgentId (more convenient than `set` for claiming)
  claim <id> [agent]       Atomically move a 'todo' ASSIGNED TO YOU -> in_progress (the --as
                           caller). Fails if already claimed — race-safe, no double-work.
                           Only the assignee may claim: a task assigned to somebody else, or
                           to nobody, is refused. Route work with `assign`/`handoff` first.
  handoff <id> <to> [note] Reassign to <to> and send them a directed inbox ping (‼️). The
                           explicit way to route a finding/bug to another agent.
  review <id> [reviewer=main] [note]
                           Move to review AND route it to <reviewer> (queue + directed ping),
                           so review has an owner instead of silting up.
  dep <id> <add|rm> <other-id>
                           Dependency (dependsOn): 'id' waits on 'other-id'; cycle- and
                           existence-checked
  set <id> <field> <json>  Set an arbitrary field to a RAW JSON value
                           (e.g. set x assignedAgentId '"main"'  or  set x isInferred true)
  archive <id>             isArchived=true
  unarchive <id>           isArchived=false
  restore                  Restore the latest pre-write backup (tasks.json.bak)
  rm <id>                  Delete a task

CONTEXT (session continuity — write context.json ONLY through these commands too, never directly)
  ctx                      Print the whole context.json (small, cheap)
  ctx-init [init] [goal]   Create context.json if missing (initPrompt, goal)
  ctx-set <field> <json>   Set a top-level field (goal|currentFocus|initPrompt|notes ...)
  ctx-decision <topic> <decision> [rationale]
                           Append a decision to the decisions array (with timestamp)
  ctx-constraint <text>    Append a standing constraint to the constraints array
  ctx-question <add|rm> <text>
                           Add / resolve an open question in the openQuestions array

FEEDBACK (about the TOOL itself, not this project's board)
  feedback <cause> <parameter> <explanation>
                           Reports a bug/observation about task.sh/claude-task-manager to a
                           GLOBAL log shared across every installed project (NOT tasks.json),
                           so the tool's developer can act on it. One line per entry:
                           [timestamp] [project/agent] - cause, parameter, explanation.
                           <explanation> should be ~3 sentences: what you wanted, what happened.
                           e.g. task.sh feedback "claim" "claim fix-login --as backend" \\
                                "Wanted to pick up an unassigned task. claim refused it with an
                                unclear error. Had to read the source to understand why." --as backend

STATUSES:    todo, in_progress, blocked, review, done
PRIORITIES:  low, normal, high, urgent

EXAMPLES (--as is required for every non-meta command)
  task.sh list todo --priority high --as main
  task.sh add fix-login "Login fix" "Login returns 500" --as main
  task.sh priority fix-login urgent --as main
  task.sh module fix-login auth --as main
  task.sh list --module auth --as main
  task.sh dep deploy add fix-login --as main   # deploy waits on fix-login
  task.sh list todo --as main                  # every open todo (main's overview)
  task.sh assign fix-login ctm-be-medior --as main   # route it — a teammate cannot take it otherwise
  task.sh next --claim --as ctm-be-medior            # take your top ready todo, race-safe
  task.sh claim fix-login --as ctm-be-medior         # take a specific todo of YOURS -> in_progress
  task.sh handoff fix-login ctm-be-medior "404 on the export route, no entryPass" --as ctm-playwright-tester
  task.sh review fix-login main "done, please review" --as ctm-be-medior
  task.sh review-queue main --as main          # what's waiting for my sign-off
  task.sh stale --older-than 24h --as main     # stuck in_progress/review tasks
  task.sh status fix-login in_progress "started" --as backend-auth
  task.sh status-many done fix-login deploy --as main
  task.sh inbox backend-auth                    # (meta: no --as) fresh events
  task.sh validate                              # (meta: no --as)
  task.sh ctx-init "Port the legacy event editor" "Full port" --as main
  task.sh ctx-constraint "Legacy: read-only, never click buttons" --as main
EOF
}

cmd_guide() {
  cat <<'EOF'
task.sh guide — STORIES: how to actually use this tool end-to-end
This is NOT a flag reference (that's `task.sh help`). It's "when X happens, run Y" —
the real sequences that make the tool work as intended, not just the individual commands.
Read this once per session, before your first task.sh call.

────────────────────────────────────────────────────────────────────────
EVERY AGENT — starting a session (once, first thing)
  task.sh lang                                    # (meta) the project's preferred language
  task.sh ctx --as <me>                           # standing goal / decisions / constraints
  (empty?) task.sh ctx-init "<what kicked this off>" "<goal>" --as <me>

MAIN — a new request comes in
  task.sh add fix-login "Login fix" "Login returns 500" --as main
  task.sh priority fix-login high --as main                # only if not "normal"
  task.sh module fix-login auth --as main                  # optional, for board filtering
  task.sh checklist fix-login add "reproduce the 500 on POST /login" "patch the null check in Login.php" "add a regression test for the null case" --as main
    # ^ each item a short SENTENCE, not a one/two-word label — "patch" tells nobody anything,
    #   "patch the null check in Login.php" is something a teammate can act on without guessing.
    # (only if already broken down at add time)
  task.sh assign fix-login <teammate> --as main             # REQUIRED — see below

WHY "assign" IS NOT OPTIONAL
  `claim` only ever succeeds for the agent a task is ALREADY assigned to — a task assigned to
  nobody, or to somebody else, is refused outright. There is no tag-based self-service: adding
  a `backend` tag does NOT make a task claimable by a backend agent. If a teammate reports "no
  claimable todo", the fix is `assign`, not a different tag.

TEAMMATE — starting your turn
  task.sh next --claim --as <me>                  # take YOUR top ready todo, race-safe
  task.sh deps fix-login --as <me>                # anything blocking it?
  task.sh checklist fix-login --as <me>            # steps already broken down for you
  ... do the work, ticking off checklist items as you finish each one ...
  task.sh files fix-login add /abs/path/Login.php --as <me>
  task.sh note fix-login "IMPL: fixed null check at Login.php:42" --as <me>
  task.sh review fix-login main "ready for review" --as <me>   # NEVER `status done` yourself

MAIN — closing the loop
  task.sh review-queue main --as main             # what's waiting on my sign-off?
  task.sh get fix-login --as main                 # the full task + its notes, before deciding
  task.sh status fix-login done --as main         # OR assign+status todo if more work remains

MID-TASK — you found something that isn't yours to fix
  task.sh add export-500 "Export 500s too" "same root cause, different route" --as <me>
  task.sh handoff export-500 <other-teammate> "same root cause, different route" --as <me>
  task.sh dep fix-login add export-500 --as <me>   # only if fix-login should wait on it

YOUR QUEUE IS EMPTY
  There's no "I'm idle" task.sh command for this — SendMessage main directly and say so.
  Don't just go quiet; an idle teammate is wasted concurrency main can't see from tasks.json.

A TASK LOOKS STUCK
  task.sh stale --older-than 24h --as main        # in_progress/review sitting too long
  task.sh history fix-login --as main             # what actually happened to it

MAIN — customizing a teammate's tools or instructions for THIS project
  These are `ctm` commands (the global CLI), NOT `task.sh` — they edit the generated agent
  DEFINITIONS in .claude/agents/, not the task board:
  ctm agent tools show ctm-be-medior                        # what tools does it have right now?
  ctm agent tools set  ctm-be-medior "Read, Edit, Bash, Grep, mcp__ide__getDiagnostics"
  ctm agent tools add  ctm-be-medior mcp__playwright__browser_navigate   # extend, don't replace
  ctm agent tools rm   ctm-be-medior Grep                   # trim (the mandatory core is protected)
  ctm agent tools unset ctm-be-medior                       # drop back to the built-in default
  ctm agent block set  ctm-be-junior ./project-conventions.md   # append project-specific rules
  ctm agent block show                                      # what's actually baked into everyone
  These only edit the PROJECT's override config — re-run `ctm init` (`--force` to overwrite
  without prompting) afterward so the change actually reaches the generated
  .claude/agents/*.md files.

REPORTING A BUG OR ODD BEHAVIOR IN THE TOOL ITSELF (not this project's board)
  task.sh feedback "<cause — command or situation>" "<parameter(s) you called it with>" \
    "<~3 sentences: what you wanted, what happened>" --as <me>
  Goes to claude-task-manager's own shared log, not this project's tasks.json, so the tool's
  developer can act on it. This is the prescribed alternative to reading the tool's own
  source (see the HARD RULE at the top of SKILL.md) — report it, don't go read or patch the
  implementation yourself.

SESSION CONTINUITY — leave a trail for your future self and every other agent
  task.sh ctx-decision "auth" "switched to JWT" "session cookies broke on mobile" --as main
  task.sh ctx-constraint "no schema migrations without senior sign-off" --as main
  task.sh ctx-question add "should export also paginate?" --as main
  task.sh ctx-question rm  "should export also paginate?" --as main   # once it's answered

Full flag-by-flag reference: task.sh help
EOF
}

cmd_init() {
  ensure_tasks_file
  echo "done: $TASKS_FILE"
}

cmd_list() {
  require_tasks_file
  local status="" tag="" agent="" prio="" module="" show_all=0 as_json=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tag)                    tag="${2:-}"; shift 2 ;;
      --agent)                  agent="${2:-}"; shift 2 ;;
      --priority|--prio)        prio="${2:-}"; shift 2 ;;
      --module|--mod)           module="${2:-}"; shift 2 ;;
      --all|--include-archived) show_all=1; shift ;;
      --json)                   as_json=1; shift ;;
      --*)                      die "unknown flag: $1" ;;
      *)                        status="$1"; shift ;;
    esac
  done
  [[ -n "$status" ]] && { is_valid_status "$status" || die "invalid status: $status (valid: $VALID_STATUSES)"; }
  local flt='.tasks[]
    | select(($all==1) or ((.isArchived // false)|not))
    | select($status=="" or (.status==$status))
    | select($tag=="" or (((.tags//[]) | index($tag)) != null))
    | select($agent=="" or (.assignedAgentId==$agent))
    | select($prio=="" or ((.priority//"normal")==$prio))
    | select($module=="" or ((.module//"")==$module))'
  if [[ $as_json == 1 ]]; then
    # checklist here is a progress SUMMARY ({done,total}), not the full array: the full item
    # texts would be noisy across a bulk task listing, but the counts are cheap and immediately
    # useful for a board progress indicator. Use `checklist <id>` for the actual items.
    jq --arg status "$status" --arg tag "$tag" --arg agent "$agent" --arg prio "$prio" --arg module "$module" --argjson all "$show_all" \
      "[ $flt | {id, status, title, priority:(.priority//\"normal\"), module:(.module//\"\"), tags:(.tags//[]), assignedAgentId, dependsOn:(.dependsOn//[]), files:(.files//[]), checklist:{done:((.checklist//[])|map(select(.done))|length), total:((.checklist//[])|length)}} ]" \
      "$TASKS_FILE"
  else
    jq -r --arg status "$status" --arg tag "$tag" --arg agent "$agent" --arg prio "$prio" --arg module "$module" --argjson all "$show_all" \
      "$flt | \"\(.id)\t[\(.status)]\t\((.priority//\"normal\") | if .==\"normal\" then \"\" else \"(\"+.+\")\" end)\t\((.module//\"\") | if .==\"\" then \"\" else \"@\"+. end)\t\(.title)\t\((.tags//[]) | if length>0 then \"#\"+join(\" #\") else \"\" end)\"" \
      "$TASKS_FILE" | column -t -s $'\t'
  fi
}

cmd_ids() {
  require_tasks_file
  local status="" show_all=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all|--include-archived) show_all=1; shift ;;
      --*) die "unknown flag: $1" ;;
      *)   status="$1"; shift ;;
    esac
  done
  jq -r --arg s "$status" --argjson all "$show_all" '
    .tasks[]
    | select(($all==1) or ((.isArchived // false)|not))
    | select($s=="" or (.status==$s))
    | .id' "$TASKS_FILE"
}

cmd_get() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: get <id>"
  local id="$1"
  task_exists "$id" || die "no such task: $id"
  jq --arg id "$id" '.tasks[]|select(.id==$id)' "$TASKS_FILE"
}

cmd_field() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: field <id> <field>"
  local id="$1" f="$2"
  task_exists "$id" || die "no such task: $id"
  jq -r --arg id "$id" --arg f "$f" '.tasks[]|select(.id==$id)|.[$f]' "$TASKS_FILE"
}

cmd_summary() {
  require_tasks_file
  local show_all=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all|--include-archived) show_all=1; shift ;;
      --*) die "unknown flag: $1" ;;
      *)   die "unknown argument: $1" ;;
    esac
  done
  jq -r --argjson all "$show_all" '
    [ .tasks[] | select(($all==1) or ((.isArchived // false)|not)) ] as $t
    | ($t|group_by(.status)|map("\(.[0].status)\t\(length)")|.[]),
    "─\t─",
    "total\t\($t|length)"
  ' "$TASKS_FILE" | column -t -s $'\t'
}

cmd_find() {
  require_tasks_file
  local q="" show_all=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all|--include-archived) show_all=1; shift ;;
      --*) die "unknown flag: $1" ;;
      *)   q="$1"; shift ;;
    esac
  done
  [[ -n "$q" ]] || die "usage: find <text> [--all]"
  jq -r --arg q "$q" --argjson all "$show_all" '
    .tasks[]
    | select(($all==1) or ((.isArchived // false)|not))
    | select((.title|ascii_downcase|contains($q|ascii_downcase))
             or ((.description//"")|ascii_downcase|contains($q|ascii_downcase)))
    | "\(.id)\t[\(.status)]\t\(.title)"
  ' "$TASKS_FILE" | column -t -s $'\t'
}

cmd_history() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: history <id>"
  local id="$1"
  task_exists "$id" || die "no such task: $id"
  jq -r --arg id "$id" '
    .tasks[]|select(.id==$id)|.history[]
    | "\(.at)\t\(.type)\t\(.fromStatus // "-") -> \(.toStatus // "-")\t\(.note // "")"
  ' "$TASKS_FILE" | column -t -s $'\t'
}

cmd_raw() {
  require_tasks_file
  cat "$TASKS_FILE"
}

cmd_add() {
  ensure_tasks_file
  [[ $# -ge 2 ]] || die "usage: add <id> <title> [description]"
  local id="$1" title="$2" desc="${3:-}"
  task_exists "$id" && die "a task with this id already exists: $id"
  local now; now="$(now_iso)"
  # checklistSeq: an internal, monotonically-increasing counter for checklist item ids (c1,
  # c2, ...) — see cmd_checklist()'s "add" case for why this can't just be derived from the
  # current checklist array's length/max (deleting the highest-numbered item must not free its
  # number for reuse; the counter survives deletions, the array doesn't).
  apply_jq --arg id "$id" --arg title "$title" --arg desc "$desc" --arg now "$now" --arg actor "$ACTOR" '
    .updatedAt = $now
    | .tasks += [{
        id: $id,
        title: $title,
        description: $desc,
        status: "todo",
        priority: "normal",
        module: "",
        tags: [],
        dependsOn: [],
        source: "claude_code",
        sourceEventId: null,
        assignedAgentId: "main",
        createdAt: $now,
        updatedAt: $now,
        playbookJobId: null,
        runId: null,
        channel: null,
        externalThreadId: null,
        lastActivityAt: $now,
        notes: [],
        files: [],
        checklist: [],
        checklistSeq: 0,
        isArchived: false,
        isInferred: false,
        history: [ { at: $now, type: "created", note: "Task created.", fromStatus: null, toStatus: "todo", by: '"$JQ_BY"', files: [] } ]
      }]'
  emit_event "$id" "created" "$title"
  echo "added: $id [todo]"
}

cmd_status() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: status <id> <status> [note]"
  local id="$1" new="$2" note="${3:-}"
  task_exists "$id" || die "no such task: $id"
  is_valid_status "$new" || die "invalid status: $new (valid: $VALID_STATUSES)"
  local now; now="$(now_iso)"
  local notval="null"; [[ -n "$note" ]] && notval="\$note"
  # by/files: see the JQ_BY / JQ_TRANSITION_FILES definitions near the top of the file (the
  # user's explicit choice — the note ties the file to the status, not directly to task.files).
  apply_jq --arg id "$id" --arg new "$new" --arg now "$now" --arg note "$note" --arg actor "$ACTOR" "
    .updatedAt = \$now
    | (.tasks[] | select(.id==\$id)) |= (
        .history += [ { at: \$now, type: \"status_changed\", note: $notval, fromStatus: .status, toStatus: \$new, by: $JQ_BY, files: $JQ_TRANSITION_FILES } ]
        | .status = \$new
        | .updatedAt = \$now
        | .lastActivityAt = \$now
      )"
  # Warn (never block) when closing a task that still has open checklist items — the
  # user's explicit call: the checklist is a lightweight helper, not a gate, and the agent
  # decides when a task is actually done. Same throttled-stderr-notice style as
  # maybe_notify_update()'s update banner, just unconditional (no TTL — this is a one-off
  # per status call, not a hot-path repeat).
  if [[ "$new" == "done" ]]; then
    local open_items
    open_items="$(jq -r --arg id "$id" '[.tasks[]|select(.id==$id)|(.checklist//[])[]|select(.done|not)]|length' "$TASKS_FILE")"
    if [[ "${open_items:-0}" -gt 0 ]]; then
      printf '\033[33m[task-manager] %s has %s unchecked checklist item(s) — marked done anyway.\033[0m\n' "$id" "$open_items" >&2
    fi
  fi
  emit_event "$id" "status:$new" "$note"
  echo "status: $id -> $new"
}

cmd_note() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: note <id> <text>"
  local id="$1" text="$2"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  # by/files: see the JQ_BY / JQ_NOTE_FILES definition (+ the rationale for the files-rm
  # restriction) near the top of the file — this way a `files add` -> `note` session ties in
  # the files picked up along the way without a parameter.
  apply_jq --arg id "$id" --arg text "$text" --arg now "$now" --arg actor "$ACTOR" '
    .updatedAt = $now
    | (.tasks[] | select(.id==$id)) |= (
        '"$JQ_NOTE_FILES"' as $delta
        | .notes += [ { at: $now, text: $text, by: '"$JQ_BY"', files: $delta } ]
        | .updatedAt = $now
        | .lastActivityAt = $now
      )'
  emit_event "$id" "note" "$text"
  echo "note appended: $id"
}

cmd_set() {
  require_tasks_file
  [[ $# -ge 3 ]] || die "usage: set <id> <field> <json-value>"
  local id="$1" field="$2" value="$3"
  task_exists "$id" || die "no such task: $id"
  # Is the value valid JSON?
  echo "$value" | jq -e . >/dev/null 2>&1 || die "value is not valid JSON: $value (quote strings: '\"text\"')"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --arg field "$field" --argjson value "$value" --arg now "$now" '
    .updatedAt = $now
    | (.tasks[] | select(.id==$id)) |= (
        .[$field] = $value
        | .updatedAt = $now
        | .lastActivityAt = $now
      )'
  emit_event "$id" "set:$field" "$value"
  echo "set: $id.$field"
}

cmd_archive() { _set_archived "$1" true; }
cmd_unarchive() { _set_archived "$1" false; }
_set_archived() {
  require_tasks_file
  local id="$1" val="$2"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --argjson val "$val" --arg now "$now" '
    .updatedAt = $now
    | (.tasks[] | select(.id==$id)) |= (.isArchived = $val | .updatedAt = $now)'
  emit_event "$id" "archived:$val" ""
  echo "isArchived=$val: $id"
}

cmd_rm() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: rm <id>"
  local id="$1"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --arg now "$now" '
    .updatedAt = $now | .tasks |= map(select(.id != $id))'
  emit_event "$id" "removed" ""
  echo "removed: $id"
}

# --- Structured fields: priority / tag / module / assign / dep ------------------------

cmd_priority() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: priority <id> <low|normal|high|urgent>"
  local id="$1" p="$2"
  task_exists "$id" || die "no such task: $id"
  local ok=0; for v in $VALID_PRIORITIES; do [[ "$p" == "$v" ]] && ok=1; done
  [[ $ok == 1 ]] || die "invalid priority: $p (valid: $VALID_PRIORITIES)"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --arg p "$p" --arg now "$now" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (.priority=$p | .updatedAt=$now | .lastActivityAt=$now)'
  emit_event "$id" "priority:$p" ""
  echo "priority: $id -> $p"
}

cmd_module() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: module <id> <module-name>  (empty string clears it)"
  local id="$1" m="$2"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --arg m "$m" --arg now "$now" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (.module=$m | .updatedAt=$now | .lastActivityAt=$now)'
  emit_event "$id" "module:$m" ""
  echo "module: $id -> ${m:-<cleared>}"
}

cmd_tag() {
  require_tasks_file
  [[ $# -ge 3 ]] || die "usage: tag <id> <add|rm> <label>"
  local id="$1" op="$2" t="$3"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  case "$op" in
    add) apply_jq --arg id "$id" --arg t "$t" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.tags = (((.tags//[]) + [$t]) | unique) | .updatedAt=$now | .lastActivityAt=$now)'
      echo "label added: $id +$t" ;;
    rm)  apply_jq --arg id "$id" --arg t "$t" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.tags = ((.tags//[]) - [$t]) | .updatedAt=$now | .lastActivityAt=$now)'
      echo "label removed: $id -$t" ;;
    *) die "unknown tag operation: $op (add|rm)" ;;
  esac
  emit_event "$id" "tag:$op" "$t"
}

cmd_files() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: files <id> [add|rm <abs-path>...]"
  local id="$1"; shift || true
  task_exists "$id" || die "no such task: $id"
  # No sub-op: just list the task's files, one per line.
  if [[ $# -eq 0 ]]; then
    jq -r --arg id "$id" '.tasks[]|select(.id==$id)|(.files//[])[]' "$TASKS_FILE"
    return 0
  fi
  local op="$1"; shift || true
  [[ $# -ge 1 ]] || die "usage: files <id> <add|rm> <abs-path> [abs-path...]"
  local paths_json now; now="$(now_iso)"
  case "$op" in
    add)
      # Enforce absolute paths — the field is a stable, machine-usable pointer to the touched
      # source files (see the agent workflow), so relative paths (caller-cwd dependent) are out.
      local p
      for p in "$@"; do [[ "$p" == /* ]] || die "files add: not an absolute path: $p"; done
      paths_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
      apply_jq --arg id "$id" --argjson add "$paths_json" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.files = (((.files//[]) + $add) | unique) | .updatedAt=$now | .lastActivityAt=$now)'
      emit_event "$id" "files:add" "$*"
      echo "files added: $id (+$#)" ;;
    rm)
      paths_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
      apply_jq --arg id "$id" --argjson del "$paths_json" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.files = ((.files//[]) - $del) | .updatedAt=$now | .lastActivityAt=$now)'
      emit_event "$id" "files:rm" "$*"
      echo "files removed: $id (-$#)" ;;
    *) die "unknown files operation: $op (add|rm)" ;;
  esac
}

# Checklist item shape: {id, text, done, addedAt, addedBy, doneAt, doneBy}. This is deliberately
# NOT the same thing as `dependsOn` (a real, independent task waiting on another) or `handoff`
# (reassigning ownership) — a checklist item never gets its own status, owner, or board card;
# it's for small steps within a task that don't deserve any of that. If a "step" needs its own
# owner/status/history, it should be a separate task (`add` + `dep`), not a checklist item.
cmd_checklist() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: checklist <id> [add <text>... | done|undo|rm <item-id>...]"
  local id="$1"; shift || true
  task_exists "$id" || die "no such task: $id"
  # No sub-op: list the items, one per line: "<item-id> [x|ready] <text>".
  if [[ $# -eq 0 ]]; then
    jq -r --arg id "$id" '
      .tasks[]|select(.id==$id)|(.checklist//[])[]
      | "\(.id)\t\(if .done then "[x]" else "[ ]" end)\t\(.text)"
    ' "$TASKS_FILE" | column -t -s $'\t'
    return 0
  fi
  local op="$1"; shift || true
  [[ $# -ge 1 ]] || die "usage: checklist <id> <add|done|undo|rm> <arg> [arg...]"
  local now; now="$(now_iso)"
  case "$op" in
    add)
      local texts_json; texts_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
      # Single atomic write for all the items in this call (same "one write, not N" idiom as
      # status-many): new ids are assigned from checklistSeq, which is bumped by the same amount.
      apply_jq --arg id "$id" --argjson texts "$texts_json" --arg now "$now" --arg actor "$ACTOR" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (
            (.checklistSeq // 0) as $start
            | ($texts | to_entries | map({
                id: ("c" + (($start + .key + 1)|tostring)),
                text: .value,
                done: false,
                addedAt: $now,
                addedBy: '"$JQ_BY"',
                doneAt: null,
                doneBy: null
              })) as $newItems
            | .checklist = ((.checklist // []) + $newItems)
            | .checklistSeq = ($start + ($texts|length))
            | .updatedAt=$now | .lastActivityAt=$now
          )'
      emit_event "$id" "checklist:add" "$*"
      echo "checklist: $id +$# item(s)" ;;
    done|undo)
      local ids_json; ids_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
      _checklist_require_items "$id" "$ids_json"
      local doneval; [[ "$op" == "done" ]] && doneval=true || doneval=false
      apply_jq --arg id "$id" --argjson ids "$ids_json" --argjson doneval "$doneval" --arg now "$now" --arg actor "$ACTOR" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (
            .checklist = ((.checklist//[]) | map(
              if (([.id] - $ids)|length)==0 then
                .done = $doneval
                | .doneAt = (if $doneval then $now else null end)
                | .doneBy = (if $doneval then '"$JQ_BY"' else null end)
              else . end))
            | .updatedAt=$now | .lastActivityAt=$now
          )'
      emit_event "$id" "checklist:$op" "$*"
      echo "checklist $op: $id ($#)" ;;
    rm)
      local ids_json; ids_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
      _checklist_require_items "$id" "$ids_json"
      apply_jq --arg id "$id" --argjson ids "$ids_json" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (
            .checklist = ((.checklist//[]) | map(select((([.id] - $ids)|length) > 0)))
            | .updatedAt=$now | .lastActivityAt=$now
          )'
      emit_event "$id" "checklist:rm" "$*"
      echo "checklist removed: $id (-$#)" ;;
    *) die "unknown checklist operation: $op (add|done|undo|rm)" ;;
  esac
}

# Fails with a helpful message (not a silent no-op) if any of the given item-ids don't exist
# on the task — shared by the done/undo/rm sub-ops of cmd_checklist().
_checklist_require_items() {
  local id="$1" ids_json="$2"
  local missing
  missing="$(jq -r --arg id "$id" --argjson ids "$ids_json" '
    (.tasks[]|select(.id==$id)|(.checklist//[])|map(.id)) as $have
    | $ids[] | select(([.] - $have)|length>0)
  ' "$TASKS_FILE" | tr '\n' ' ')"
  [[ -z "${missing// /}" ]] || die "no such checklist item(s) on $id: $missing"
}

cmd_assign() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: assign <id> <agent>"
  local id="$1" agent="$2"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  apply_jq --arg id "$id" --arg a "$agent" --arg now "$now" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (.assignedAgentId=$a | .updatedAt=$now | .lastActivityAt=$now)'
  emit_event "$id" "assign" "$agent"
  echo "assigned: $id -> $agent"
}

cmd_dep() {
  require_tasks_file
  [[ $# -ge 3 ]] || die "usage: dep <id> <add|rm> <other-id>"
  local id="$1" op="$2" other="$3"
  task_exists "$id" || die "no such task: $id"
  local now; now="$(now_iso)"
  case "$op" in
    add)
      [[ "$id" == "$other" ]] && die "a task cannot depend on itself: $id"
      task_exists "$other" || die "no such task (dependency): $other"
      # Forbid a direct cycle: if 'other' already depends on 'id'.
      local rev; rev="$(jq -r --arg o "$other" --arg id "$id" \
        '[.tasks[]|select(.id==$o)|(.dependsOn//[])[]]|index($id)' "$TASKS_FILE")"
      [[ "$rev" != "null" ]] && die "cyclic dependency: $other already depends on: $id"
      apply_jq --arg id "$id" --arg o "$other" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.dependsOn = (((.dependsOn//[]) + [$o]) | unique) | .updatedAt=$now | .lastActivityAt=$now)'
      emit_event "$id" "dep:add" "$other"
      echo "dependency: $id ⛔ waits on: $other" ;;
    rm)
      apply_jq --arg id "$id" --arg o "$other" --arg now "$now" '
        .updatedAt=$now
        | (.tasks[]|select(.id==$id)) |= (.dependsOn = ((.dependsOn//[]) - [$o]) | .updatedAt=$now | .lastActivityAt=$now)'
      emit_event "$id" "dep:rm" "$other"
      echo "dependency removed: $id -$other" ;;
    *) die "unknown dep operation: $op (add|rm)" ;;
  esac
}

cmd_deps() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: deps <id>"
  local id="$1"
  task_exists "$id" || die "no such task: $id"
  jq -r --arg id "$id" '
    . as $root
    | def stat($i): ($root.tasks[]|select(.id==$i)|.status) // "?";
      ($root.tasks[]|select(.id==$id)) as $t
    | "Task: \($id) [\($t.status)]",
      "",
      "Waiting on (dependsOn):",
      ( if (($t.dependsOn//[])|length)==0 then "  – none"
        else ($t.dependsOn[] | "  \(.) [\(stat(.))]") end ),
      "",
      "Blocks (referenced by):",
      ( [ $root.tasks[] | select(((.dependsOn//[])|index($id)) != null) | "  \(.id) [\(.status)]" ]
        | if length==0 then "  – none" else .[] end )
  ' "$TASKS_FILE"
}

# _ready_todo_ids [agent]
# Ordered ids of ready todos (dependency-satisfied), highest priority first. Shared by
# `next` (display) and `next --claim` (atomic pick-and-claim).
#
# With <agent>, only that agent's OWN todos — matching what claim will actually allow. In
# practice cmd_next always passes one, since `next` is not in actor_optional() and so requires
# --as; the empty case only keeps this helper total for any other caller.
_ready_todo_ids() {
  local agent="${1:-}"
  jq -r --arg agent "$agent" '
    . as $root
    | def doneish($i): ($root.tasks[]|select(.id==$i)) as $d
        | ($d==null) or ($d.status=="done") or ($d.isArchived==true);
      def prio_rank: {"urgent":0,"high":1,"normal":2,"low":3}[(.priority//"normal")] // 2;
      [ $root.tasks[]
        | select((.isArchived//false)|not)
        | select(.status=="todo")
        | select( $agent == "" or (.assignedAgentId // "") == $agent )
        | select( ((.dependsOn//[]) | map(doneish(.)) | all) ) ]
      | sort_by(prio_rank, .createdAt)
      | .[].id
  ' "$TASKS_FILE"
}

cmd_next() {
  require_tasks_file
  local do_claim=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --claim) do_claim=1; shift ;;
      --*)     die "unknown flag: $1" ;;
      *)       shift ;;
    esac
  done
  if [[ $do_claim == 1 ]]; then
    [[ -n "$ACTOR" ]] || die "next --claim needs --as <agent>"
    # Walk candidates in priority order; the first one we can atomically claim is ours.
    # If another agent claimed it in the race window, claim() leaves it untouched and we
    # fall through to the next candidate.
    local id
    while IFS= read -r id; do
      [[ -z "$id" ]] && continue
      if _try_claim "$id" "$ACTOR"; then
        echo "claimed: $id -> $ACTOR [in_progress]"
        jq -r --arg id "$id" '.tasks[]|select(.id==$id)|"  \(.title)"' "$TASKS_FILE"
        return 0
      fi
    done < <(_ready_todo_ids "$ACTOR")
    echo "no claimable todo assigned to $ACTOR (none assigned, all taken, blocked, or done)"
    return 0
  fi
  local list
  list="$(_ready_todo_ids "$ACTOR")"
  if [[ -z "$list" ]]; then
    echo "no available todo assigned to $ACTOR (none assigned, all blocked, or done)"
    return 0
  fi
  # Same scoping as _ready_todo_ids above: what is listed must be exactly what the caller
  # could actually claim, or `next` would advertise other agents' work.
  jq -r --arg agent "$ACTOR" '
    . as $root
    | def doneish($i): ($root.tasks[]|select(.id==$i)) as $d
        | ($d==null) or ($d.status=="done") or ($d.isArchived==true);
      def prio_rank: {"urgent":0,"high":1,"normal":2,"low":3}[(.priority//"normal")] // 2;
      [ $root.tasks[]
        | select((.isArchived//false)|not)
        | select(.status=="todo")
        | select( $agent == "" or (.assignedAgentId // "") == $agent )
        | select( ((.dependsOn//[]) | map(doneish(.)) | all) ) ]
      | sort_by(prio_rank, .createdAt)
      | .[] | "\(.id)\t[\(.priority//"normal")]\t\(.title)"
  ' "$TASKS_FILE" | column -t -s $'\t'
}

# --- Coordination: atomic claim / directed handoff / review routing --------------
# The atomicity guarantee lives INSIDE the jq filter, executed under the mkdir-lock in
# apply_jq: two agents racing to claim the same todo are serialized, and only the first flips
# it to in_progress. The loser's guard sees a non-todo status and writes nothing.
#
# The guard also enforces OWNERSHIP: only the assignee may claim. A task assigned to somebody
# else — or to nobody — is refused, rather than being taken over and reassigned to the caller
# (which is what claim used to do). With a tiered roster this is what keeps the levels apart:
# without it a junior polling for work would happily take a task meant for the senior, since
# nothing but prose stopped it. Routing is now exclusively main's job, via assign/handoff.
# Returns 0 if the caller now owns the task in_progress, 1 otherwise (no output — callers report).
_try_claim() {
  local id="$1" agent="$2" now; now="$(now_iso)"
  # by/files: see JQ_BY / JQ_TRANSITION_FILES near the top of the file. 'by' is the caller
  # ($ACTOR), NOT necessarily $a (the claim's target can be a different agent than the one
  # who issued the command).
  apply_jq --arg id "$id" --arg a "$agent" --arg now "$now" --arg actor "$ACTOR" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (
        if .status=="todo" and (.assignedAgentId // "") == $a then
          .history += [{at:$now, type:"status_changed", note:("claimed by "+$a), fromStatus:.status, toStatus:"in_progress", by:'"$JQ_BY"', files:'"$JQ_TRANSITION_FILES"'}]
          | .status="in_progress" | .assignedAgentId=$a | .updatedAt=$now | .lastActivityAt=$now
        else . end)'
  local owner st
  owner="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.assignedAgentId' "$TASKS_FILE")"
  st="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.status' "$TASKS_FILE")"
  if [[ "$owner" == "$agent" && "$st" == "in_progress" ]]; then
    emit_event "$id" "claim" "$agent"
    return 0
  fi
  return 1
}

cmd_claim() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: claim <id> [agent]   (agent defaults to the --as caller)"
  local id="$1" agent="${2:-$ACTOR}"
  [[ -n "$agent" ]] || die "no agent: pass --as <agent> or claim <id> <agent>"
  task_exists "$id" || die "no such task: $id"
  if _try_claim "$id" "$agent"; then
    echo "claimed: $id -> $agent [in_progress]"
  else
    local owner st
    owner="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.assignedAgentId // ""' "$TASKS_FILE")"
    st="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.status' "$TASKS_FILE")"
    if [[ "$st" != "todo" ]]; then
      die "cannot claim $id: it is [$st], not 'todo' (owner: ${owner:-nobody})"
    elif [[ -z "$owner" ]]; then
      die "cannot claim $id: it is not assigned to anyone. Only the assignee may claim — ask main to assign it (task.sh assign $id $agent --as main)"
    else
      die "cannot claim $id: it is assigned to \"$owner\", not to \"$agent\". Only the assignee may claim — leave it alone, or ask main to reassign it"
    fi
  fi
}

cmd_handoff() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: handoff <id> <to-agent> [note]"
  local id="$1" to="$2" note="${3:-}"
  task_exists "$id" || die "no such task: $id"
  local from; from="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.assignedAgentId // ""' "$TASKS_FILE")"
  local now; now="$(now_iso)"
  # HANDOFF: prefix (in English, like the rest of the engine's outgoing text) — this triggers
  # noteKind()'s k-handoff badge on the board (see js/Utils.js's NOTE_KIND_STEMS); the script
  # derives it, no manual tagging needed from the agent.
  local trail="HANDOFF: 🤝 ${from:-?} → $to"; [[ -n "$note" ]] && trail="$trail — $note"
  # by/files: same logic as cmd_note (JQ_BY / JQ_NOTE_FILES, see near the top of the file).
  apply_jq --arg id "$id" --arg to "$to" --arg now "$now" --arg trail "$trail" --arg actor "$ACTOR" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (
        '"$JQ_NOTE_FILES"' as $delta
        | .assignedAgentId=$to
        | .notes += [{at:$now, text:$trail, by:'"$JQ_BY"', files:$delta}]
        | .updatedAt=$now | .lastActivityAt=$now)'
  local msg="→$to"; [[ -n "$note" ]] && msg="$msg: $note"
  emit_event "$id" "handoff" "$msg" "$to"
  echo "handoff: $id  ${from:-?} → $to"
}

cmd_review() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: review <id> [reviewer=main] [note]"
  local id="$1" reviewer="${2:-main}" note="${3:-}"
  task_exists "$id" || die "no such task: $id"
  local worker; worker="$(jq -r --arg id "$id" '.tasks[]|select(.id==$id)|.assignedAgentId // ""' "$TASKS_FILE")"
  local now; now="$(now_iso)"
  local notval="null"; [[ -n "$note" ]] && notval="\$note"
  # by/files: see JQ_BY / JQ_TRANSITION_FILES near the top of the file.
  apply_jq --arg id "$id" --arg reviewer "$reviewer" --arg now "$now" --arg note "$note" --arg actor "$ACTOR" "
    .updatedAt=\$now
    | (.tasks[]|select(.id==\$id)) |= (
        .history += [{at:\$now, type:\"status_changed\", note:$notval, fromStatus:.status, toStatus:\"review\", by:$JQ_BY, files:$JQ_TRANSITION_FILES}]
        | .status=\"review\" | .assignedAgentId=\$reviewer | .updatedAt=\$now | .lastActivityAt=\$now)"
  emit_event "$id" "status:review" "$note"
  local msg="from ${worker:-?}"; [[ -n "$note" ]] && msg="$msg: $note"
  emit_event "$id" "review-request" "$msg" "$reviewer"
  echo "review: $id -> [review], reviewer=$reviewer (from ${worker:-?})"
}

# Tasks sitting in review, oldest first, with age since they entered review. Optionally only
# those assigned to <reviewer> (the review queue for one agent).
cmd_review_queue() {
  require_tasks_file
  local reviewer="${1:-}"
  jq -r --arg who "$reviewer" '
    def secs($t): ($t|sub("\\.[0-9]+Z$";"Z")|fromdateiso8601);
    def entered_review:
      ([.history[]? | select(.toStatus=="review") | .at] | last) // .lastActivityAt // .updatedAt;
    (now) as $n
    | [ .tasks[]
        | select((.isArchived//false)|not)
        | select(.status=="review")
        | select($who=="" or (.assignedAgentId==$who)) ]
    | sort_by(entered_review)
    | if length==0 then "review queue empty" + (if $who=="" then "" else " for \($who)" end)
      else (.[] | "\(.id)\t\(((($n - secs(entered_review))/3600)*10|floor)/10)h\t@\(.assignedAgentId // "?")\t\(.title)") end
  ' "$TASKS_FILE" | column -t -s $'\t'
}

# Tasks held but idle: in a "working" status (default in_progress + review) with no activity
# for longer than the threshold. Surfaces the review/in_progress graveyard so main can re-route.
cmd_stale() {
  require_tasks_file
  local threshold_s=86400   # default 24h
  local -a statuses=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --older-than) threshold_s="$(_parse_duration "${2:-24h}")"; shift 2 ;;
      --older-than=*) threshold_s="$(_parse_duration "${1#*=}")"; shift ;;
      --*) die "unknown flag: $1" ;;
      *) statuses+=("$1"); shift ;;
    esac
  done
  [[ ${#statuses[@]} -eq 0 ]] && statuses=(in_progress review)
  local st_json; st_json="$(printf '%s\n' "${statuses[@]}" | jq -R . | jq -s .)"
  local now_s; now_s="$(date +%s)"
  local cutoff=$(( now_s - threshold_s ))
  jq -r --argjson cutoff "$cutoff" --argjson statuses "$st_json" --argjson now "$now_s" '
    def secs($t): ($t|sub("\\.[0-9]+Z$";"Z")|fromdateiso8601);
    [ .tasks[]
      | select((.isArchived//false)|not)
      | select(.status as $s | $statuses | index($s))
      | select(secs(.lastActivityAt // .updatedAt) < $cutoff) ]
    | sort_by(.lastActivityAt // .updatedAt)
    | if length==0 then "no stale tasks"
      else (.[] | "\(.id)\t[\(.status)]\t\(((($now - secs(.lastActivityAt // .updatedAt))/3600)*10|floor)/10)h idle\t@\(.assignedAgentId // "?")\t\(.title)") end
  ' "$TASKS_FILE" | column -t -s $'\t'
}

# Parse a duration like "24h", "2d", "90m", or a bare number (seconds) into seconds.
_parse_duration() {
  local d="$1" n unit
  n="${d%[hdmsHDMS]}"; unit="${d#$n}"
  [[ "$n" =~ ^[0-9]+$ ]] || die "invalid duration: $d (use e.g. 24h, 2d, 90m)"
  case "$unit" in
    h|H) echo $(( n * 3600 )) ;;
    d|D) echo $(( n * 86400 )) ;;
    m|M) echo $(( n * 60 )) ;;
    s|S|"") echo "$n" ;;
    *) die "invalid duration unit: $unit (use h|d|m|s)" ;;
  esac
}

cmd_reopen() {
  require_tasks_file
  [[ $# -ge 1 ]] || die "usage: reopen <id> [status=todo]"
  local id="$1" new="${2:-todo}"
  task_exists "$id" || die "no such task: $id"
  is_valid_status "$new" || die "invalid status: $new (valid: $VALID_STATUSES)"
  local now; now="$(now_iso)"
  # by/files: see JQ_BY / JQ_TRANSITION_FILES near the top of the file — reopen is also a real transition.
  apply_jq --arg id "$id" --arg new "$new" --arg now "$now" --arg actor "$ACTOR" '
    .updatedAt=$now
    | (.tasks[]|select(.id==$id)) |= (
        .history += [{at:$now, type:"reopened", note:"Task reopened.", fromStatus:.status, toStatus:$new, by:'"$JQ_BY"', files:'"$JQ_TRANSITION_FILES"'}]
        | .status=$new | .isArchived=false | .updatedAt=$now | .lastActivityAt=$now)'
  emit_event "$id" "status:$new" "reopened"
  echo "reopened: $id -> $new"
}

cmd_status_many() {
  require_tasks_file
  [[ $# -ge 2 ]] || die "usage: status-many <status> <id> [id...]"
  local new="$1"; shift
  is_valid_status "$new" || die "invalid status: $new (valid: $VALID_STATUSES)"
  local id
  for id in "$@"; do task_exists "$id" || die "no such task: $id"; done
  local ids_json; ids_json="$(printf '%s\n' "$@" | jq -R . | jq -s .)"
  local now; now="$(now_iso)"
  # by/files: see JQ_BY / JQ_TRANSITION_FILES near the top of the file. Under |=, '.' applies
  # independently to each selected task, so the fragments look at each task's own notes/history
  # per task — they don't get mixed up across the tasks of the bulk operation.
  apply_jq --arg new "$new" --arg now "$now" --argjson ids "$ids_json" --arg actor "$ACTOR" '
    .updatedAt=$now
    | (.tasks[] | select((.id as $i | $ids | index($i)) != null)) |= (
        .history += [{at:$now, type:"status_changed", note:null, fromStatus:.status, toStatus:$new, by:'"$JQ_BY"', files:'"$JQ_TRANSITION_FILES"'}]
        | .status=$new | .updatedAt=$now | .lastActivityAt=$now)'
  for id in "$@"; do emit_event "$id" "status:$new" ""; done
  echo "status (bulk): $* -> $new"
}

# --- Robustness: validate / restore ----------------------------------------

cmd_validate() {
  require_tasks_file
  jq -e . "$TASKS_FILE" >/dev/null 2>&1 || { echo "VALIDATION: FAILED – invalid JSON"; return 1; }
  local report
  report="$(jq -r --arg statuses "$VALID_STATUSES" --arg prios "$VALID_PRIORITIES" '
    ($statuses|split(" ")) as $vs
    | ($prios|split(" ")) as $vp
    | ([.tasks[].id]) as $ids
    | ( [ .tasks[]
          | . as $t
          | ( if ($t.id//"")=="" then "a task has an empty/missing id" else empty end ),
            ( if ($t.title//"")=="" then "\($t.id): missing title" else empty end ),
            ( if ($vs|index($t.status)) then empty else "\($t.id): invalid status: \($t.status)" end ),
            ( if (($t.priority//"normal") as $p | $vp|index($p)) then empty else "\($t.id): invalid priority: \($t.priority)" end ),
            ( ($t.dependsOn//[])[] as $d | select(($ids|index($d))==null) | "\($t.id): broken dependency -> \($d)" ),
            ( ($t.checklist//[]) as $cl
              | if ($cl|type) != "array" then "\($t.id): checklist is not an array" else empty end ),
            ( ($t.checklist//[]) as $cl | select(($cl|type)=="array") | $cl[] as $c
              | if ($c.id//"")=="" then "\($t.id): a checklist item has an empty/missing id"
                elif ($c|has("text")|not) or (($c.text|type)!="string") then "\($t.id): checklist item \($c.id//"?"): missing/invalid text"
                elif ($c|has("done")|not) or (($c.done|type)!="boolean") then "\($t.id): checklist item \($c.id//"?"): missing/invalid done flag"
                else empty end ),
            ( ($t.checklist//[]) as $cl | select(($cl|type)=="array")
              | ($cl|map(.id)|group_by(.)|map(select(length>1)|.[0])) as $dups
              | $dups[] | "\($t.id): duplicate checklist item id: \(.)" ),
            ( ($t.checklist//[]) as $cl | select(($cl|type)=="array")
              | ( [$cl[] | (.id // "") | select(test("^c[0-9]+$")) | (sub("^c";"")|tonumber)] ) as $nums
              | (if ($nums|length)>0 then ($nums|max) else 0 end) as $maxItemNum
              | ($t.checklistSeq // 0) as $seq
              | if $seq < $maxItemNum then "\($t.id): checklistSeq (\($seq)) is behind the highest checklist item id (c\($maxItemNum)) — likely hand-edited; new items could collide with an existing id" else empty end )
        ] )
    + ( [.tasks[].id] | group_by(.) | map(select(length>1)|.[0]) | map("duplicate id: \(.)") )
    | .[]
  ' "$TASKS_FILE")"
  if [[ -n "$report" ]]; then
    echo "$report"
    echo "─"
    echo "VALIDATION: FAILED ($(printf '%s\n' "$report" | grep -c . ) issue(s))"
    return 1
  fi
  echo "VALIDATION: OK ($(jq '.tasks|length' "$TASKS_FILE") task(s))"
}

cmd_restore() {
  [[ -f "$BACKUP_FILE" ]] || die "no backup: $BACKUP_FILE"
  acquire_lock
  [[ -f "$TASKS_FILE" ]] && cp "$TASKS_FILE" "$TASKS_FILE.prerestore" 2>/dev/null || true
  cp "$BACKUP_FILE" "$TASKS_FILE"
  release_lock
  echo "restored from backup: $BACKUP_FILE -> $TASKS_FILE (previous: $TASKS_FILE.prerestore)"
}

# --- Inbox: per-agent, deduplicated event notification ---------------------------
# `inbox <agent>`: returns events generated by OTHER agents since <agent>'s cursor (not its
# own), then advances the cursor. SILENT if there's nothing new (empty output) — so the hook
# only injects when there's something to inject. On first connect it does NOT dump the whole
# past: the cursor is set to the current end, and only events from then on are returned. The
# caller agent is supplied by the PostToolUse hook (from the --as flag); this command itself
# does NOT require --as.
cmd_inbox() {
  [[ $# -ge 1 ]] || die "usage: inbox <agent>"
  local agent="$1"
  [[ -f "$EVENTS_FILE" ]] || return 0
  local maxseq; maxseq="$(wc -l < "$EVENTS_FILE" 2>/dev/null | tr -d ' ')"
  [[ -z "$maxseq" ]] && maxseq=0
  mkdir -p "$CURSORS_DIR" 2>/dev/null || true
  # Filename-safe cursor key (agent names are typically [A-Za-z0-9_-], but be defensive).
  local safe; safe="$(printf '%s' "$agent" | tr -c 'A-Za-z0-9_.-' '_')"
  local cursor_file="$CURSORS_DIR/$safe"
  if [[ ! -f "$cursor_file" ]]; then
    printf '%s\n' "$maxseq" > "$cursor_file" 2>/dev/null || true
    return 0
  fi
  local seen; seen="$(cat "$cursor_file" 2>/dev/null || echo 0)"
  [[ "$seen" =~ ^[0-9]+$ ]] || seen=0
  # Advance the cursor first (so we don't loop on our own events either), then filter.
  printf '%s\n' "$maxseq" > "$cursor_file" 2>/dev/null || true
  jq -r --argjson seen "$seen" --arg me "$agent" '
      select(.seq > $seen and .by != $me)
      | (if (.to // "")==$me then "‼️ " else "📬 " end)
        + "[\(.task)] \(.by) → \(.kind)" + (if ((.text//"")|length)==0 then "" else ": \(.text)" end)
    ' "$EVENTS_FILE" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Commands — context.json (session continuity)
# ---------------------------------------------------------------------------
# context.json must ALSO only be written through these commands (never direct
# Read/Write/Edit), so there's a single atomic writer for both stores.

cmd_ctx() {  # the whole context.json (small, cheap to read)
  require_context_file
  cat "$CONTEXT_FILE"
}

cmd_ctx_init() {
  local init="${1:-}" goal="${2:-}"
  if [[ -f "$CONTEXT_FILE" ]]; then
    echo "already exists: $CONTEXT_FILE"
    return 0
  fi
  ensure_context_file
  local now; now="$(now_iso)"
  apply_ctx --arg init "$init" --arg goal "$goal" --arg now "$now" \
    '.updatedAt=$now | .initPrompt=$init | .goal=$goal'
  echo "done: $CONTEXT_FILE"
}

cmd_ctx_set() {
  ensure_context_file
  [[ $# -ge 2 ]] || die "usage: ctx-set <field> <json-value>"
  local field="$1" value="$2"
  echo "$value" | jq -e . >/dev/null 2>&1 \
    || die "value is not valid JSON: $value (quote strings: '\"text\"')"
  local now; now="$(now_iso)"
  apply_ctx --arg field "$field" --argjson value "$value" --arg now "$now" \
    '.updatedAt=$now | .[$field]=$value'
  echo "context set: $field"
}

cmd_ctx_decision() {
  ensure_context_file
  [[ $# -ge 2 ]] || die "usage: ctx-decision <topic> <decision> [rationale]"
  local topic="$1" decision="$2" rationale="${3:-}"
  local now; now="$(now_iso)"
  apply_ctx --arg topic "$topic" --arg decision "$decision" \
            --arg rationale "$rationale" --arg now "$now" \
    '.updatedAt=$now
     | .decisions += [{at:$now, topic:$topic, decision:$decision, rationale:$rationale}]'
  echo "decision recorded: $topic"
}

cmd_ctx_constraint() {
  ensure_context_file
  [[ $# -ge 1 ]] || die "usage: ctx-constraint <text>"
  local text="$1"
  local now; now="$(now_iso)"
  apply_ctx --arg text "$text" --arg now "$now" \
    '.updatedAt=$now | .constraints += [$text]'
  echo "constraint added"
}

cmd_ctx_question() {
  ensure_context_file
  [[ $# -ge 2 ]] || die "usage: ctx-question <add|rm> <text>"
  local op="$1" text="$2"
  local now; now="$(now_iso)"
  case "$op" in
    add)
      apply_ctx --arg text "$text" --arg now "$now" \
        '.updatedAt=$now | .openQuestions += [$text]'
      echo "open question added" ;;
    rm|resolve)
      apply_ctx --arg text "$text" --arg now "$now" \
        '.updatedAt=$now | .openQuestions |= map(select(. != $text))'
      echo "question resolved" ;;
    *) die "unknown ctx-question operation: $op (add|rm)" ;;
  esac
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

# Commands for which --as is NOT required (meta / diagnostic / called by the hook itself).
# Every other command REQUIRES --as <agent> (identifies the caller, so the hook can inject
# the right inbox, and emit_event records it as `by`).
actor_optional() {
  case "$1" in
    help|-h|--help|guide|inbox|init|validate|check|restore|raw|lang) return 0 ;;
    *) return 1 ;;
  esac
}

# Reports the project's preferred language, set from the board's current UI language
# (api/index.php writes it to $TM_DIR/.board-lang on every write — see ApiClient.js).
# Deliberately NOT stored in any task/note: this is board-level state, read fresh on every
# call. Meta command (no --as needed) — agent templates (templates/agents/*.md.tmpl)
# REQUIRE every agent to call this once per session instead of being passively nagged on
# every task.sh invocation.
cmd_lang() {
  local f="$TM_DIR/.board-lang" lang=""
  [[ -f "$f" ]] && lang="$(tr -d '[:space:]' < "$f" 2>/dev/null)"
  case "$lang" in
    hu) echo "hu — this project's preferred language is Hungarian: reply and work in Hungarian for the rest of this session." ;;
    en) echo "en — this project's preferred language is English." ;;
    *)  echo "(unset) — no project-level language preference; use your default." ;;
  esac
}

# cmd_feedback — reports a bug/observation about the TOOL ITSELF (task.sh/claude-task-manager),
# not this project's task board. Written to a GLOBAL log shared across every project this tool
# is installed into (engine/feedback.sh), so --as identifies who filed it and the project is
# recorded automatically from TM_DIR — deliberately NOT a meta command: knowing the source
# project and agent is exactly what makes the log useful to the tool's developer.
cmd_feedback() {
  [[ $# -ge 3 ]] || die 'usage: feedback "<cause — command/situation>" "<parameter(s) you called it with>" "<~3 sentences: what you wanted, what happened>" --as <agent>'
  local cause="$1" param="$2" body="$3"
  local project; project="$(basename "$TM_DIR")"
  log_feedback "$cause" "$param" "$body" "$ACTOR" "$project" \
    || die "could not write feedback (lock contention?) — try again"
  echo "logged: $FEEDBACK_FILE"
}

# --- Update notice (silent, cached, non-blocking) --------------------------------
# The coding agents never find out on their own when a newer claude-task-manager version is
# published, so surface it via the one channel they DO read on every command: task.sh's stderr.
# But task.sh is the hot path — a network round-trip on every mutation would add real latency
# (see engine/check-update.sh's header). So the networked check is split off:
#   (1) occasionally, gated by BOTH a random draw and a TTL, we spawn a fully DETACHED
#       background subshell that sources check-update.sh and writes its result to a small flag
#       file — this never blocks the current command; and
#   (2) every (non-meta) call cheaply reads that flag file (no network) and, if an update is
#       known available, prints a throttled one-line notice to stderr.
# Opt out entirely with TM_NO_UPDATE_CHECK=1.
UPDATE_FLAG="$TM_DIR/.update-available"       # non-empty (holds branch name) when origin is ahead
UPDATE_CHECKED="$TM_DIR/.update-checked-at"   # mtime = when the networked check last ran
UPDATE_NOTIFIED="$TM_DIR/.update-notified-at" # mtime = when we last printed the notice

# Seconds since <file> was last modified; a large number if it doesn't exist. Portable
# (BSD/macOS `stat -f %m`, GNU/Linux `stat -c %Y`).
_age_secs() {
  local f="$1" m now
  [[ -e "$f" ]] || { echo 999999999; return; }
  m="$(stat -f %m "$f" 2>/dev/null || stat -c %Y "$f" 2>/dev/null || echo 0)"
  now="$(date +%s)"
  echo $(( now - m ))
}

maybe_notify_update() {
  # Skip hot/meta commands — especially inbox, which the PostToolUse hook runs constantly.
  case "$1" in help|-h|--help|inbox|init|validate|check|raw) return 0 ;; esac
  [[ "${TM_NO_UPDATE_CHECK:-0}" == "1" ]] && return 0

  # The package repo root is one level up from engine/ (where this script lives). The update
  # mechanism is git-pull based, so it only means anything for a git checkout.
  local repo_root; repo_root="$(dirname "$SCRIPT_DIR")"
  [[ -d "$repo_root/.git" ]] || return 0

  # (1) Refresh the cache occasionally, entirely in the background (never blocks this call).
  #     The random gate spreads checks across calls; the TTL bounds how often the network is
  #     actually hit even under heavy traffic from several agents. We stamp UPDATE_CHECKED
  #     BEFORE spawning so concurrent invocations within the window don't all pile on.
  local ttl="${TM_UPDATE_TTL:-21600}"   # 6h between networked checks
  local prob="${TM_UPDATE_PROB:-8}"     # ~1-in-8 calls even considers a refresh
  if (( RANDOM % prob == 0 )) && [[ "$(_age_secs "$UPDATE_CHECKED")" -ge "$ttl" ]]; then
    touch "$UPDATE_CHECKED" 2>/dev/null || true
    ( source "$SCRIPT_DIR/check-update.sh" 2>/dev/null \
        && refresh_update_cache "$repo_root" "$UPDATE_FLAG" ) >/dev/null 2>&1 &
    disown 2>/dev/null || true
  fi

  # (2) If an update is known available, print a THROTTLED notice to stderr, so it doesn't
  #     repeat on every command in a session (agents run task.sh many times).
  if [[ -s "$UPDATE_FLAG" ]]; then
    local ntl="${TM_UPDATE_NOTICE_TTL:-3600}"   # at most once per hour, per project store
    if [[ "$(_age_secs "$UPDATE_NOTIFIED")" -ge "$ntl" ]]; then
      touch "$UPDATE_NOTIFIED" 2>/dev/null || true
      local branch; branch="$(tr -d '[:space:]' < "$UPDATE_FLAG" 2>/dev/null || echo main)"
      printf '\033[33m[task-manager] A newer claude-task-manager version is available on origin/%s. Tell the human to update the package: git -C %s pull\033[0m\n' \
        "${branch:-main}" "$repo_root" >&2
    fi
  fi
  return 0
}

main() {
  local cmd="${1:-help}"
  shift || true
  maybe_notify_update "$cmd"

  # Extract --as <agent> from ANYWHERE in the arguments; the rest goes into array A.
  local -a A=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --as) ACTOR="${2:-}"; shift 2 || shift ;;
      --as=*) ACTOR="${1#--as=}"; shift ;;
      *) A+=("$1"); shift ;;
    esac
  done

  # Require --as (except for meta commands). This way the hook always knows the caller,
  # and every event is written with a `by`.
  if ! actor_optional "$cmd"; then
    [[ -n "$ACTOR" ]] || die "--as <agent> is required (e.g. --as main). Command: $cmd"
  fi

  # "${A[@]}" would throw 'unbound variable' under bash 3.2 (macOS) + set -u when empty;
  # the ${A[@]+...} guard avoids that.
  set -- ${A[@]+"${A[@]}"}

  case "$cmd" in
    help|-h|--help) cmd_help ;;
    guide)     cmd_guide ;;
    feedback)  cmd_feedback "$@" ;;
    inbox)     cmd_inbox "$@" ;;
    init)      cmd_init "$@" ;;
    list|ls)   cmd_list "$@" ;;
    ids)       cmd_ids "$@" ;;
    get)       cmd_get "$@" ;;
    field)     cmd_field "$@" ;;
    summary)   cmd_summary "$@" ;;
    find)      cmd_find "$@" ;;
    history)   cmd_history "$@" ;;
    raw)       cmd_raw "$@" ;;
    next)      cmd_next "$@" ;;
    claim)     cmd_claim "$@" ;;
    handoff)   cmd_handoff "$@" ;;
    review)    cmd_review "$@" ;;
    review-queue|reviewq) cmd_review_queue "$@" ;;
    stale)     cmd_stale "$@" ;;
    deps)      cmd_deps "$@" ;;
    validate|check) cmd_validate "$@" ;;
    lang)      cmd_lang "$@" ;;
    add)       cmd_add "$@" ;;
    status)    cmd_status "$@" ;;
    status-many|status-multi) cmd_status_many "$@" ;;
    reopen)    cmd_reopen "$@" ;;
    note)      cmd_note "$@" ;;
    set)       cmd_set "$@" ;;
    priority|prio) cmd_priority "$@" ;;
    module|mod) cmd_module "$@" ;;
    tag)       cmd_tag "$@" ;;
    files)     cmd_files "$@" ;;
    checklist) cmd_checklist "$@" ;;
    assign)    cmd_assign "$@" ;;
    dep)       cmd_dep "$@" ;;
    archive)   cmd_archive "$@" ;;
    unarchive) cmd_unarchive "$@" ;;
    restore)   cmd_restore "$@" ;;
    rm|remove) cmd_rm "$@" ;;
    ctx|context)    cmd_ctx "$@" ;;
    ctx-init)       cmd_ctx_init "$@" ;;
    ctx-set)        cmd_ctx_set "$@" ;;
    ctx-decision)   cmd_ctx_decision "$@" ;;
    ctx-constraint) cmd_ctx_constraint "$@" ;;
    ctx-question)   cmd_ctx_question "$@" ;;
    *) die "unknown command: $cmd (help: task.sh help)" ;;
  esac
}

main "$@"
